import Footer from './components/Footer';
import GlobalBreadcrumbs from './components/GlobalBreadcrumbs';
import Navbar from './components/Navbar';
import './globals.css';

export const metadata = {
  title: 'Webrizen | Website Design & Development Agency In Assam, India',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <GlobalBreadcrumbs/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
